#!/bin/bash
# Compile core memory files into a single file
# Usage: ./compile.sh
# Note: HTML comments (<!-- -->) are stripped from source files

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT_FILE="$SCRIPT_DIR/compiled/core-memory-compiled.md"

echo "Compiling core memory files..."

# Create header
cat > "$OUTPUT_FILE" << 'EOF'
<!-- COMPILED CORE MEMORY FILE -->
<!-- Auto-generated by compile.sh - Do not edit directly -->
<!-- Edit the source files in core-memory/ folder instead -->

EOF

# Function to strip HTML comments and clean up empty lines
strip_comments() {
    # Remove single-line comments: <!-- ... -->
    # Remove multi-line comments: <!-- ... \n ... -->
    # Then clean up excessive blank lines (more than 2 consecutive)
    sed '/<!--.*-->/d; /<!--/,/-->/d' | sed '/^$/N;/^\n$/d'
}

# Combine files in order
for file in "$SCRIPT_DIR"/[0-9]-*.md; do
    if [ -f "$file" ]; then
        filename=$(basename "$file")
        echo "  Adding: $filename"
        echo "" >> "$OUTPUT_FILE"
        echo "<!-- ========== SOURCE: $filename ========== -->" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        # Strip comments before adding to output
        strip_comments < "$file" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    fi
done

echo ""
echo "✓ Compiled to: $OUTPUT_FILE"
echo "✓ Total lines: $(wc -l < "$OUTPUT_FILE")"
